# ansible用playbook
- hosts: localhost
  connection: local
  sudo: no

  tasks:
    #- name: 基本ツールインストール(RedHat系)
    #  when: ansible_os_family == 'RedHat'
    #  sudo: yes
    #  yum:
    #    name: "{{ item }}"
    #    state: latest
    #  with_items:
    #    - yum-fastestmirror
    #    - "@Development tools"
    #    - rpmdevtools
    #    - createrepo
    #    - yum-utils
    #    - vim-enhanced
    #    - screen
    #    - ansible
    #
    #- name: 基本ツールインストール(Debian系)
    #  when: ansible_os_family == 'Debian'
    #  sudo: yes
    #  apt:
    #    name: "{{ item }}"
    #    state: latest
    #  with_items:
    #    - build-essential
    #    - unzip
    #    - golang
    #    - re2c
    #    - vim-enhanced
    #    - screen

    - name: dotfilesコピー
      git:
        dest: ~/src/github.com/hirak/dotfiles
        repo: git://github.com/hirak/dotfiles.git
        accept_hostkey: yes
        update: yes

    - name: dotfilesをリンク
      shell: sh link.sh; source ~/.bash_profile
      args:
        chdir: ~/src/github.com/hirak/dotfiles/
        creates: ~/.vim/bundle/neobundle.vim

    # ghq
    - name: get latest ghq version
      shell: curl -sI https://github.com/motemen/ghq/releases/latest | awk -F'/' '/^Location:/{print $NF}'
      register: ghq_latest_version
      args:
        creates: ~/bin/ghq

    - name: Download latest ghq
      shell: |
        mkdir ghq_tmp
        cd ghq_tmp
        curl -sL -o ghq.zip https://github.com/motemen/ghq/releases/download/{{ ghq_latest_version.stdout }}/ghq_{{ ansible_system | lower }}_amd64.zip
        unzip ghq.zip
        mv ghq ~/bin/ghq
        chmod +x ~/bin/ghq
        cd ..
        rm -rf ghq_tmp
      args:
        creates: ~/bin/ghq

    # peco
    - name: get latest peco version
      shell: curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'
      register: peco_latest_version
      args:
        creates: ~/bin/peco

    - name: Download latest peco
      shell: |
        curl -sL https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_{{ ansible_system | lower }}_amd64.tar.gz | \
        tar zx -C ~/bin/ --strip=1 --wildcards '*/peco'
        chmod +x ~/bin/peco
      args:
        creates: ~/bin/peco

    # direnv
    - name: get latest direnv version
      shell: go get github.com/direnv/direnv
      args:
        creates: ~/bin/direnv

    # jq
    - name: install jq
      shell: |
        if [ "{{ ansible_system }}" = "Darwin" ]; then
          type=osx
        else
          type=linux
        fi
        curl -sLo ~/bin/jq http://stedolan.github.io/jq/download/${type}64/jq
        chmod +x ~/bin/jq

    # node.js
    - name: nodebrewをインストール
      shell: curl -L git.io/nodebrew | perl - setup
      args:
        creates: ~/.nodebrew

    # php
    - name: php-buildを単独インストール
      git:
        dest: ~/src/github.com/hirak/php-build
        repo: git://github.com/hirak/php-build.git
        accept_hostkey: true
        update: true

    - name: php-buildのセットアップ
      command: ln -s ~/src/github.com/hirak/php-build/bin/php-build ~/bin/php-build
      args:
        creates: ~/bin/php-build

    - name: ~/.php/を作成
      command: mkdir -p ~/.php
      args:
        creates: ~/.php

    - name: composerダウンロード
      shell: |
        curl -sLo ~/bin/composer http://packagist.jp/composer.phar
        chmod +x ~/bin/composer
      args:
        creates: ~/bin/composer

    - name: phpunitダウンロード
      shell: |
        curl -sLo ~/bin/phpunit http://packagist.jp/phpunit.phar
        chmod +x ~/bin/phpunit
      args:
        creates: ~/bin/phpunit

    # ruby
    - name: ruby-buildを単独インストール
      git:
        dest: ~/src/github.com/sstephenson/ruby-build
        repo: git://github.com/sstephenson/ruby-build.git
        accept_hostkey: true
        update: true

    - name: ruby-buildのセットアップ
      command: ln -s ~/src/github.com/sstephenson/ruby-build/bin/ruby-build ~/bin/ruby-build
      args:
        creates: ~/bin/ruby-build

    - name: ~/.ruby/を作成
      command: mkdir -p ~/.ruby
      args:
        creates: ~/.ruby
