# vim: set ft=ruby:
tap 'caskroom/cask'
tap 'homebrew/dupes'
cask 'google-japanese-ime'
cask 'opera'
cask 'flash-player'

brew 'openssl'
brew 'lua'
brew 'vim', args: ['with-lua']
brew 'bison'
brew 'autoconf'
brew 'automake'
brew 'bison'
brew 're2c'
brew 'libjpeg'
brew 'libpng'
brew 'libmcrypt'
brew 'libxml2'
brew 'go'
brew 'zlib'
brew 'screen'
brew 'curl'
brew 'wget'
brew 'libiconv'
brew 'readline'
brew 'pngquant'
brew 'libedit'
#link 'openssl', args: ['force']
#link 'zlib', args: ['force']
#link 'curl', args: ['force']
